const TYPE_COLORS = {
  "하이퍼스케일": "#a2fc4d",
  "코로케이션": "#c7fd94",
  "AI/클라우드": "#d6febc",
  "통신사 IDC": "#e84dc4",
  "파이프라인": "#f194db",
  "기업 자사용": "#8e3ce1",
  "공공 통합전산": "#bb8aed",
  "공공기관 자사": "#ddc4f6",
  "공공기관 DC": "#ddc5f6",
  "지자체 전산": "#ede0fa",
  "계획/예정": "#f29ee0",
  "기타": "#999"
};
const CAT_LABELS = {
  "Government DC": ["공공기관 DC",  "#ddc5f6"],
  "Hyperscale":    ["하이퍼스케일", "#a2fc4d"],
  "Colocation":    ["코로케이션",   "#c7fd94"],
  "Telecom DC":    ["통신사 IDC",   "#e84dc4"],
  "Enterprise":    ["기업 자사용",  "#8e3ce1"],
  "Planned":       ["계획/예정",    "#f29ee0"]
};
const CAT_ORDER = ["Government DC","Hyperscale","Colocation","Telecom DC","Enterprise","Planned"];
const DROUGHT_COLORS = {"1": "#fce4e4", "2": "#f5b8b0", "3": "#e07060", "4": "#c0302a", "5": "#8b0000"};

// Normalize incoming dataset (new dataset uses category/cat_raw)
const CATEGORY_TO_TYPE = Object.fromEntries(
  Object.entries(CAT_LABELS).map(([k, v]) => [k, v[0]])
);
function normalizeDcType(dc) {
  const existing = (dc?.type ?? '').toString().trim();
  if (existing) return existing;

  const cat = (dc?.category ?? dc?.cat_raw ?? '').toString().trim();
  if (cat && CATEGORY_TO_TYPE[cat]) return CATEGORY_TO_TYPE[cat];
  if (cat && TYPE_COLORS[cat]) return cat;

  const sector = (dc?.sector ?? '').toString();
  if (sector.includes('공공')) return '공공기관 DC';

  const y = parseInt((dc?.year ?? '').toString(), 10);
  if (Number.isFinite(y) && y > new Date().getFullYear()) return '계획/예정';

  return cat || '기타';
}

// Drought tooltip: offline id -> municipality name mapping
// Generated by matching drought polygon bbox-center to KOSTAT 2018 municipalities bbox.
const DROUGHT_ID_TO_NAME = {
  "0":"시흥시","1":"안산시상록구","2":"의왕시","3":"남양주시","4":"용인시처인구","5":"파주시","6":"이천시","7":"안성시","8":"김포시","9":"화성시","10":"광주시","11":"파주시","12":"포천시","13":"이천시","14":"연천군","15":"포천시","16":"양평군","17":"춘천시","18":"원주시","19":"강릉시","20":"강릉시","21":"태백시","22":"속초시","23":"삼척시","24":"홍천군","25":"원주시","26":"영월군","27":"평창군","28":"영월군","29":"철원군","30":"철원군","31":"양구군","32":"인제군","33":"고성군","34":"양양군","35":"청주시상당구","36":"충주시","37":"영월군","38":"청주시상당구","39":"옥천군","40":"영동군","41":"증평군","42":"진천군","43":"괴산군","44":"음성군","45":"단양군","46":"천안시동남구","47":"공주시","48":"보령시","49":"아산시","50":"서산시","51":"논산시","52":"공주시","53":"서산시","54":"금산군","55":"부여군","56":"부여군","57":"청양군","58":"홍성군","59":"예산군","60":"태안군","61":"전주시완산구","62":"군산시","63":"익산시","64":"정읍시","65":"남원시","66":"군산시","67":"전주시덕진구","68":"진안군","69":"무주군","70":"진안군","71":"완주군","72":"순창군","73":"고창군","74":"군산시","75":"목포시","76":"여수시","77":"순천시","78":"나주시","79":"광양시","80":"담양군","81":"곡성군","82":"구례군","83":"여수시","84":"여수시","85":"화순군","86":"장흥군","87":"강진군","88":"해남군","89":"영암군","90":"무안군","91":"나주시","92":"영광군","93":"고창군","94":"완도군","95":"진도군","96":"신안군","97":"포항시북구","98":"경주시","99":"김천시","100":"안동시","101":"구미시","102":"단양군","103":"영천시","104":"상주시","105":"문경시","106":"영천시","107":"군위군","108":"안동시","109":"청송군","110":"영양군","111":"영덕군","112":"경산시","113":"고령군","114":"김천시","115":"칠곡군","116":"안동시","117":"봉화군","118":"울진군","119":"울릉군","120":"창원시의창구","121":"진주시","122":"통영시","123":"사천시","124":"김해시","125":"밀양시","126":"통영시","127":"울주군","128":"의령군","129":"의령군","130":"창녕군","131":"고성군","132":"남해군","133":"광양시","134":"산청군","135":"산청군","136":"거창군","137":"합천군","138":"제주시","139":"제주시","140":"종로구","141":"사상구","142":"기장군","143":"동구","144":"달서구","145":"중구","146":"강화군","147":"옹진군","148":"서구","149":"중구","150":"중구","151":"울주군","152":"세종시","153":"수원시장안구","154":"성남시수정구","155":"의정부시","156":"안양시만안구","157":"부천시","158":"광명시","159":"평택시","160":"동두천시","161":"안산시단원구","162":"고양시덕양구","163":"서초구","164":"구리시","165":"남양주시","166":"오산시"
};

// ── MAP INIT ──────────────────────────────────────────────
const map = L.map('map', {
  center: [36.5, 127.8],
  zoom: 7,
  zoomControl: false,
  attributionControl: false
});
L.control.zoom({ position: 'bottomright' }).addTo(map);

// Dark basemap
L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}{r}.png', {
  subdomains: 'abcd', maxZoom: 19
}).addTo(map);

// Drought choropleth
const droughtLayer = L.geoJSON(window.APP_DATA.DISTRICTS, {
  style: f => ({
    fillColor: DROUGHT_COLORS[f.properties.drought || 2],
    fillOpacity: 0.4,
    color: 'rgba(255,255,255,0.06)',
    weight: 0.1,
    strokeOpacity: 0,
  }),
  onEachFeature: (f, l) => {
    const labels = {1:'매우 낮은 취약',2:'낮은 취약',3:'보통 취약',4:'높은 취약',5:'매우 높은 취약'};
    const droughtLabel = labels[f.properties.drought || 2];
    const id = f?.properties?.id;
    const name = DROUGHT_ID_TO_NAME[String(id)] || `구역 ${id ?? ''}`.trim();
    l.bindTooltip(`${name}: ${droughtLabel}`, {
      sticky: true, direction: 'top', offset: [0, -4],
    });
  }
}).addTo(map);

// Labels layer on top
L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_only_labels/{z}/{x}/{y}{r}.png', {
  subdomains: 'abcd', maxZoom: 19, zIndex: 500
}).addTo(map);

// ── TYPE FILTERS ──────────────────────────────────────────
const ALL_TYPES = Object.keys(TYPE_COLORS);
const activeTypes = new Set(ALL_TYPES);
const markersByType = {};
const layerGroup = L.layerGroup().addTo(map);

// Build type filter UI
const filtersEl = document.getElementById('type-filters');
const typeCounts = {};
window.APP_DATA.DC_DATA.forEach(d => { d.type = normalizeDcType(d); });
window.APP_DATA.DC_DATA.forEach(d => { typeCounts[d.type] = (typeCounts[d.type]||0) + 1; });

ALL_TYPES.forEach(type => {
  if (!typeCounts[type]) return;
  const btn = document.createElement('button');
  btn.className = 'type-btn';
  btn.dataset.type = type;
  btn.innerHTML = `
    <div class="type-dot" style="background:${TYPE_COLORS[type]}"></div>
    <span class="type-name">${type}</span>
    <span class="type-count">${typeCounts[type]||0}</span>
  `;
  btn.addEventListener('click', () => toggleType(type, btn));
  filtersEl.appendChild(btn);
});

function toggleType(type, btn) {
  if (activeTypes.has(type)) {
    activeTypes.delete(type);
    btn.classList.add('off');
    markersByType[type]?.forEach(m => layerGroup.removeLayer(m));
  } else {
    activeTypes.add(type);
    btn.classList.remove('off');
    markersByType[type]?.forEach(m => layerGroup.addLayer(m));
  }
  updateStatTotal();
}

// ── MARKERS ───────────────────────────────────────────────
window.APP_DATA.DC_DATA.forEach(dc => {
  const color = TYPE_COLORS[dc.type] || '#999';
  const itMw = Number.isFinite(Number(dc.it_mw)) ? Number(dc.it_mw) : 0;
  const r = Math.max(5, Math.min(18, Math.sqrt(itMw) * 2.2));
  const isApprox = !((dc.accuracy || '').toString().trim().startsWith('✓'));
  const hasWater = !!(dc.water && dc.water !== '');

  const markerDotHtml = `
    <div class="dc-marker" style="
      width:${r*2}px; height:${r*2}px; border-radius:50%;
      background:${color}; opacity:${isApprox ? 0.55 : 0.92};
      border: ${isApprox ? '1.5px dashed rgba(255,255,255,0.6)' : '1.5px solid rgba(255,255,255,0.8)'};
      box-shadow: 0 0 ${r}px ${color}66, 0 0 ${r*0.5}px ${color}44;
    "></div>
  `;
  const markerHtml = hasWater ? `
    <div style="position:relative;width:${r*2}px;height:${r*2}px">
      ${markerDotHtml}
      <div style="position:absolute;top:-2px;right:-2px;width:7px;height:7px;border-radius:50%;background:#00d4ff;border:1px solid #000;font-size:5px;line-height:7px;text-align:center">💧</div>
    </div>
  ` : markerDotHtml;

  const icon = L.divIcon({
    html: markerHtml, className: '',
    iconSize: [r*2, r*2], iconAnchor: [r, r]
  });

  const marker = L.marker([dc.lat, dc.lon], { icon, zIndexOffset: Math.round(itMw) })
    .bindTooltip(
      `<b>${dc.name}</b><br>${(Number.isFinite(itMw) && itMw) ? itMw : '-'} MW · ${dc.type}` +
      (isApprox ? ' · 위치추정' : '') +
      (hasWater ? ' · 💧EIA' : ''),
      { direction:'top', offset:[0,-r] }
    )
    .on('click', () => openDetail(dc, color));

  if (!markersByType[dc.type]) markersByType[dc.type] = [];
  markersByType[dc.type].push(marker);
  layerGroup.addLayer(marker);
});

// ── DETAIL PANEL ──────────────────────────────────────────
function openDetail(dc, color) {
  const panel = document.getElementById('detail-panel');
  const mapEl = document.getElementById('map');
  
  document.getElementById('detail-type-badge').textContent = dc.type;
  document.getElementById('detail-type-badge').style.cssText = `
    background:${color}22; color:${color};
    border:1px solid ${color}66; display:inline-block;
    padding:2px 8px; border-radius:3px;
    font-family:var(--mono); font-size:9px;
    text-transform:uppercase; letter-spacing:0.08em; margin-bottom:8px;
  `;
  document.getElementById('detail-name').textContent = dc.name;
  
  const rows = [
    ['운영주체', dc.operator],
    ['지역', dc.region],
    ['섹터', dc.sector],
    ['준공연도', dc.year],
    ['부지', (Number.isFinite(Number(String(dc.area ?? '').replace(/,/g, ''))) ? Number(String(dc.area).replace(/,/g, '')).toLocaleString('ko-KR') + '㎡' : '-')],
    ['IT 용량', (Number.isFinite(Number(dc.it_mw)) ? Number(dc.it_mw) : '-') + ' MW'],
    ['PUE', dc.pue],
    ['냉각방식', dc.cooling],
    ['주소', dc.addr],
    ['좌표 정확도', dc.accuracy],
    dc.note ? ['비고', dc.note] : null
  ].filter(Boolean);

  document.getElementById('detail-body').innerHTML = rows.map(([k,v]) => `
    <div class="detail-row">
      <span class="detail-key" style="${k === 'IT 용량' ? 'color:#00e5ff;' : (k === 'PUE' ? 'color:#a2fc4d;' : '')}" >${k}</span>
      <span class="detail-val" style="${k === 'IT 용량' ? 'color:#00e5ff;' : (k === 'PUE' ? 'color:#a2fc4d;' : '')}">${v}</span>
    </div>`).join('');

  panel.classList.add('open');
  mapEl.classList.add('detail-open');
  map.invalidateSize();
}

function closeDetail() {
  document.getElementById('detail-panel').classList.remove('open');
  document.getElementById('map').classList.remove('detail-open');
  map.invalidateSize();
}

// ── SEARCH ────────────────────────────────────────────────
document.getElementById('search-input').addEventListener('input', e => {
  const q = e.target.value.toLowerCase().trim();
  layerGroup.clearLayers();
  
  window.APP_DATA.DC_DATA.forEach((dc, i) => {
    if (!activeTypes.has(dc.type)) return;
    const match = !q || dc.name.toLowerCase().includes(q) || 
                  dc.operator.toLowerCase().includes(q) ||
                  dc.addr.toLowerCase().includes(q);
    if (match) {
      // find marker
      const m = markersByType[dc.type]?.[markersByType[dc.type].findIndex(
        mx => mx.getLatLng().lat === dc.lat && mx.getLatLng().lng === dc.lon
      )];
      if (m) layerGroup.addLayer(m);
    }
  });
});

// Rebuild markers on search clear
document.getElementById('search-input').addEventListener('keydown', e => {
  if (e.key === 'Escape') {
    e.target.value = '';
    e.target.dispatchEvent(new Event('input'));
  }
});

// ── SECTOR BARS ───────────────────────────────────────────
const sectorEl = document.getElementById('sector-bars');
const sectorData = {};
window.APP_DATA.DC_DATA.forEach(d => { sectorData[d.sector] = (sectorData[d.sector]||0)+1; });
const sectorTotal = window.APP_DATA.DC_DATA.length;

Object.entries(sectorData).sort((a,b)=>b[1]-a[1]).forEach(([sector, count]) => {
  const pct = (count/sectorTotal*100).toFixed(0);
  sectorEl.innerHTML += `
    <div style="margin-bottom:6px">
      <div style="display:flex;justify-content:space-between;margin-bottom:3px">
        <span style="font-family:var(--mono);font-size:11px;color:var(--text2)">${sector}</span>
        <span style="font-family:var(--mono);font-size:11px;color:var(--text3)">${count}</span>
      </div>
      <div style="background:rgba(255,255,255,0.06);border-radius:2px;height:3px;overflow:hidden">
        <div style="width:${pct}%;height:100%;background:rgba(232,77,196,0.6);border-radius:2px"></div>
      </div>
    </div>`;
});

// ── REGION BARS ───────────────────────────────────────────
function getRegionFromAddr(addr) {
  const pairs = [
    ['서울','서울'], ['경기','경기'], ['인천','인천'], ['강원','강원'],
    ['충북','충북'], ['충남','충남'], ['세종','대전/세종'], ['대전','대전/세종'],
    ['전북','전북'], ['전남','전남'], ['광주','광주'], ['경북','경북'],
    ['경남','경남'], ['부산','부산'], ['울산','울산'], ['대구','대구'], ['제주','제주']
  ];
  for (const [key, region] of pairs) {
    if ((addr || '').includes(key)) return region;
  }
  return '기타';
}

const regionEl = document.getElementById('region-bars');
const regionData = {};
window.APP_DATA.DC_DATA.forEach(d => {
  const region = (d.region || '').trim() || getRegionFromAddr(d.addr || '');
  regionData[region] = (regionData[region] || 0) + 1;
});
const regionTotal = window.APP_DATA.DC_DATA.length;

Object.entries(regionData).sort((a,b)=>b[1]-a[1]).slice(0,12).forEach(([region, count]) => {
  const pct = (count/regionTotal*100).toFixed(0);
  regionEl.innerHTML += `
    <div style="margin-bottom:6px">
      <div style="display:flex;justify-content:space-between;margin-bottom:3px">
        <span style="font-family:var(--mono);font-size:11px;color:var(--text2)">${region}</span>
        <span style="font-family:var(--mono);font-size:11px;color:var(--text3)">${count}</span>
      </div>
      <div style="background:rgba(255,255,255,0.06);border-radius:2px;height:3px;overflow:hidden">
        <div style="width:${pct}%;height:100%;background:rgba(162,252,77,0.7);border-radius:2px"></div>
      </div>
    </div>`;
});

// ── STAT UPDATE ───────────────────────────────────────────
function updateStatTotal() {
  const active = window.APP_DATA.DC_DATA.filter(d => activeTypes.has(d.type));
  // stat-total is fixed (overall total), only update EIA water stat by toggles.
  document.getElementById('stat-water').textContent =
    active.filter(d => !!(d.water && d.water !== '')).length;
}

// Initial stat render
document.getElementById('stat-total').textContent = window.APP_DATA.DC_DATA.length;
updateStatTotal();
